workflow:
    rules:
        -
            if: '$CI_PIPELINE_SOURCE == ''merge_request_event'''
        -
            if: $CI_COMMIT_TAG
        -
            if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
variables:
    MYSQL_ROOT_PASSWORD: root
    typo3DatabaseName: typo3
    typo3DatabaseHost: mariadb
    typo3DatabaseUsername: root
    typo3DatabasePassword: root
stages:
    - code-quality
    - code-tests
    - security-scanner
code-quality:
    parallel:
        matrix:
            -
                php_version:
                    - '8.2'
                typo3_version:
                    - '11.5'
    cache:
        key:
            files:
                - composer.lock
            prefix: 'php${php_version}-typo3{typo3_version}-'
        paths:
            - ./cache/composer
    before_script:
        - 'set -xe'
        - 'apt-get update -yqq'
        - 'apt-get install git libzip-dev unzip parallel libxml2-utils wget wait-for-it libicu-dev -yqq'
        - 'php -r "readfile(''http://getcomposer.org/installer'');" | php -- --install-dir=/usr/local/bin/ --filename=composer'
        - 'chmod +x /usr/local/bin/composer'
        - 'composer config cache-dir ./cache/composer'
        - 'cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini'
        - 'awk ''/^error_reporting = E_ALL/{print "error_reporting = E_ALL & ~E_DEPRECATED"; next}1'' /usr/local/etc/php/php.ini > temp.ini && mv temp.ini /usr/local/etc/php/php.ini'
        - 'composer require typo3/cms-core ^${typo3_version} --no-progress --ignore-platform-req=ext-intl'
        - 'composer install --no-progress --ignore-platform-req=ext-intl'
    image: 'php:${php_version}'
    stage: code-quality
    script:
        - 'composer ci:static'
code-tests:
    parallel:
        matrix:
            -
                php_version: {  }
                typo3_version: {  }
    cache:
        key:
            files:
                - composer.lock
            prefix: 'php${php_version}-typo3{typo3_version}-'
        paths:
            - ./cache/composer
    before_script:
        - 'set -xe'
        - 'apt-get update -yqq'
        - 'apt-get install git libzip-dev unzip parallel libxml2-utils wget wait-for-it libicu-dev -yqq'
        - 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli'
        - 'php -r "readfile(''http://getcomposer.org/installer'');" | php -- --install-dir=/usr/local/bin/ --filename=composer'
        - 'chmod +x /usr/local/bin/composer'
        - 'composer config cache-dir ./cache/composer'
        - 'cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini'
        - 'awk ''/^error_reporting = E_ALL/{print "error_reporting = E_ALL & ~E_DEPRECATED"; next}1'' /usr/local/etc/php/php.ini > temp.ini && mv temp.ini /usr/local/etc/php/php.ini'
        - 'composer require typo3/cms-core ^${typo3_version} --no-progress --ignore-platform-req=ext-intl'
        - 'composer install --no-progress --ignore-platform-req=ext-intl'
    image: 'php:${php_version}'
    stage: code-tests
    services:
        - 'mariadb:10'
    script:
        - 'composer ci:coverage'
semgrep:
    image: semgrep/semgrep
    script: 'semgrep scan --config auto --error .'
    stage: security-scanner
