services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Verdigado\CalendarizeExternal\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Verdigado\CalendarizeExternal\Command\ScheduleCals:
    tags:
      -
        name: console.command
        command: 'calendarize-external:schedule-cals'
        description: 'run all scheduled external calendars'
        schedulable: true
